# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 266782e82cde3b5e58c760f797ed321f78f6e2f6a0cd6ccdd3979892f0b6c61316ce43246e9a8adf9569d3cd1c8ee989bc12b5f489d2d189ab6433ff6b33748f

test:
  secret_key_base: 96b5a6b4cc1eae53d1d6580069d5fd46e8c4ef67809e856a7efcc10839abed07146f6ee6eca42c01eb522b1d88549532436df681ed48ee25ab9fa7f5d504d015

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
